### ISSUE TITLE
Avoid worse case scenarios where an encoded ampersand breaks the transaction tickets URL

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-ticketing#3] opened 2018-05-09 20:57 UTC
It was reported in a priority support token that some users were getting an error message instead of their tickets. The error message is:

> The request for the "ee-txn-tickets-url" route has a malformed url. 

What may be happening is the email client isn't decoding the `&amp;` in the transactions tickets URL. 

You can see an example of what happens by visiting the following URL:
https://ee4m.eventespresso.com/?ee=ee-txn-tickets-url&amp;token=1-2437789f4d4aedb12f351ee63719f5a4

**Comment by mnelson4** [comment] 2018-05-09 21:34
> What may be happening is the email client isn't decoding the &amp; in the transactions tickets URL.

Usually the email clients shouldn't need to.

Which characters are used for URL querystring separators is defined by a PHP ini variable (http://php.net/manual/en/ini.core.php#ini.arg-separator.input and http://php.net/manual/en/ini.core.php#ini.arg-separator.output) so I'm suspicious that those don't line up. But it's also possible the messages are URL encoded the strings unnecessarily.

Anyways, if I were to do this I'd see if I coudl reproduce locally witout fiddling with those settings, then I'd see what fiddling with them did

**Comment by joshfeck** [comment] 2018-05-10 13:17
You might also check the source of the generated emails too, because it appears the ampersands are decoded in the source of the html.

**Comment by mnelson4** [comment] 2018-07-06 20:47
Just for my record, on my localhost, using `amp;` instead of `&` and it worked ok, so this issue depends on the server configuration.

**Comment by mnelson4** [comment] 2018-07-06 21:02
oh weird- although the tickets URL doesn't seem to behave the same, its broke for me too locally... I'll need to double-check

**Comment by mnelson4** [comment] 2018-07-06 22:48
yeah this still works for me locally: 
https://ee71-develop.test/registration-checkout/?uts=1530909848&amp;e_reg_url_link=1-6820ee4e6ac8e5f6440de5a66255a5e4&amp;step=payment_options&amp;revisit=1#checkout
but this doesn't
https://ee71-develop.test/?ee=ee-txn-tickets-approved-url&amp;token=1-97454966d861cfbc3c587d40068814dd

weird eh... I'll have to follow the execution path

**Comment by mnelson4** [comment] 2018-07-13 18:49
Also as an FYI, if you have this HTML on a page
``
<h1>hello</h1>
<a href="http://ee71-develop.test?foo=var&amp;baz=bash">the link</a>
```
that's technically what XHTML wants (because `&`s should be escaped in XHTML attributes). 
BUT browsers will decode that into `http://ee71-develop.test?foo=var&baz=bash` when the sending the user to that URL. (I tried it in firefox). So even if our HTML had URLS using `&amp` instead of `&` in them, which from my testing we don't, the browser would still "fix" those URLs to use `&` as the querystring separator instead of `&amp;`.
Side note: Drupal, at one point, for an unknown reason, defaulted to setting `arg_separator.output` to `&amp;`, see https://www.drupal.org/node/2476237. IMO this was probably to make URLs in HTML elements escape the `&`s by default, instead of doing the escaping on every HTML attribute. Anyways, the point is: people play with that setting, and sometimes even web frameworks play with it.

**Comment by mnelson4** [comment] 2018-07-13 19:53
although, from my testing, if I add `ini_set('arg_separator.output',     ';');` to my `wp-config.php`, URLs are still built with `&`s, including in the generated emails. This is because we're using `add_query_arg` which uses WordPress' `build_query` which always uses `&` as the argument seperator, regardless of what's set in php.ini.
So I can't reproduce by purposefully setting a bad `arg_separator.output`.

**Comment by mnelson4** [comment] 2018-07-13 20:03
So in summary:
* I don't know how URLs using `&amp;` as the argument seperator are being generated. Purposefully setting a bad php.ini `arg_seperator.output` doesn't reproduce it; we always use `&` as the argument seperator, even in URLs inside HTML element attributes
* on no planet will `&amp;` ever be a valid argument seperator, because `arg_seperator.input`'s value is a LIST of characters that will be considered separators, so you can't ever set it so the sequence `&amp;` will be considered a single separator

SO, the mystery is how are people getting URLs that use `&amp;` for the separator, because I don't see any way that can happen in the code...

**Comment by mnelson4** [comment] 2018-07-13 20:14
aha, here's a bit of a clue: if I copy-and-paste a ticket URL like `https://ee71-develop.test/?ee=ee-txn-tickets-approved-url&token=1-97454966d861cfbc3c587d40068814dd` into a message body, that `&` will get replaced with `&amp;` in the email body. 
Eg, if from the registrations list table, I select a registration and click "Send Bulk Email" and then create an email with this body:
```
<a href="https://ee71-develop.test/?ee=ee-txn-tickets-approved-url&token=1-97454966d861cfbc3c587d40068814dd">Click here for your tickets!</a>
```
That `&` will get URL-encoded, so the source of the generated email's body will actually be:
```
<a href=3D"https://ee71-develop.test/?ee=3Dee-txn-tickets-approved-url=
&amp;token=3D1-97454966d861cfbc3c587d40068814dd">juts click here</a>
```

BUT, when someone clicks on that link, the browser automatically decodes the URL to again be `https://ee71-develop.test/?ee=ee-txn-tickets-approved-url&token=1-97454966d861cfbc3c587d40068814dd`, so the user is sent to the right place.

So, if you were using a browser that doesn't do that (or an email client that doesn't do that) you'd reproduce this issue. But according to XHTML, you should use `&`s in URLs should be escaped when they're inside an HTML element attribute (see https://www.sitepoint.com/php-and-standards-arg_separatoroutput/, although the article is pretty confusing because, it seems, everywhere they put `&amp;` were decoded to also be `&`). So that might be a clue, but by itself it doesn't explain this issue.

**Comment by mnelson4** [comment] 2018-07-13 20:22
@joshfeck can you help me get some more info on this issue?

What I'd like to know to debug further (most useful info first):
* where can I reproduce this from end-to-end? (I know if you have a URL that uses `&amp;` for the separator, that won't ever work. But I need to identify why users are being directed to URLs like that).
* is this problem happening for automatically generated emails? or does this problem happen only for batch emails where they manually copy-and-paste the URL into the email body?
* what email client were users using? (in case it's not converting `&amp;`s in URLs in HTML element attributes into `&`)
* what browser are users using? (similar to above)
* what is the site's `arg_seperator.input` and `arg_seperator.output` values (just in case those have weird values and somehow they affect this, although I don't think they do)

**Comment by mnelson4** [comment] 2018-07-13 21:19
chatted with Josh about this in slack. A few more details:
* the site owner experiencing the issue was using SendGrid as their email provider, and it seems SendGrid had a bug when their "Click Tracking" feature changed URLs into their special tracking URLs, where their special tracking URL would forward users onto a URL containing `&amp;`s instead of `&`
* the site owner fixed the issue by switching to MailGun
* I tried to reproduce with SendGrid, but the emails that got sent from my localhost using SendGrid had the correct URL in them, even when using SendGrid's "Click Tracking" feature. So it's possible the bug was fixed

Josh also suggested maybe we could automatically change `&amp;`s in URLs to `&`s... I think we would need to do that before PHP parsed the querystring, or do it after the fact and replace `$_GET` and our `Request`. We could do it whenever a GET parameter isn't present. Although thinking about it, I'd be inclined to only do this once this is confirmed to still be an issue.

Josh also suggested at least making the error text more understandable to everyday users. Although I think someone else should suggest some improved text, that's not my forte

**Comment by mnelson4** [comment] 2018-07-13 21:35
Passing back to Seth to decide where to go from here. 
The summary is:
* it seems this was a bug in SendGrid that caused this, but it may have been fixed
* we could automatically redirect users from URLs that use `&amp` to ones that use `&`, but that might be tricky to implement (it's mostly Brent's domain anyway, as it relates to modules and requests)
* at very least, we could improve the text. If so, maybe Josh or Lorenzo might like to suggest an exact string to use

**Comment by joshfeck** [comment] 2018-07-13 21:50
Suggested change:

Whoa! Dude! Something went wrong and we're unable to display your ticket. Please contact the website administrator and inform them that the ticket URL is invalid.

If you're comfortable with a little do-it-yourself repairing, you could try changing the `&amp` in the address bar to simply `&`.

**Comment by mnelson4** [comment] 2018-07-17 18:22
Ya thanks @joshfeck. So I'll look into customizing that message...

**Comment by mnelson4** [comment] 2018-07-25 23:33
PR created: https://github.com/eventespresso/eea-ticketing/pull/5

**Comment by mnelson4** [comment] 2018-07-27 18:56
pull request merged. We both attempt to automatically fix the URLs, and if we can't, we give a more user-friendly error message.

**Closed by mnelson4** 2018-07-27 18:56 UTC
Labels: category:messaging-&-messengers, type:bug 🐞
